language: node_js
sudo: false
services:
  - mysql
node_js:
  - "node"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run prettier:ci
  - npm run test
notifications:
  email: false
