---
version: '3'
services:
  db:
    image: mysql:5.7.21
    restart: unless-stopped
    networks:
      - voting
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - './db:/var/lib/mysql'

  api:
    image: oleville-voting:latest
    depends_on: [ db ]
    restart: unless-stopped
    networks:
      - voting
    ports:
      - 0.0.0.0:80:4000
    environment:
      - NODE_ENV
    volumes:
      - './config/config.json:/srv/vote/config/config.json'
      - './config.js:/srv/vote/config.js'
      - './env.js:/srv/vote/env.js'

networks:
  voting:
