#!/bin/bash

ROOT_FOLDER="$(dirname $0)/.."

if [ -z "$MYSQL_ROOT_PASSWORD" ];
then
	echo -n "Enter root password to set on the mysql container: "
	read -s MYSQL_ROOT_PASSWORD
	echo "Thanks. :)"

	export MYSQL_ROOT_PASSWORD
else
	export MYSQL_ROOT_PASSWORD
fi

if [ -z "$NODE_ENV" ];
then
	export NODE_ENV=development
else
	export NODE_ENV
fi

export MYSQL_DATABASE=OlevilleVoting_$NODE_ENV

docker-compose -f $ROOT_FOLDER/docker-compose.yml up -d
